### ISSUE TITLE
ID for 1.8 servers

### ISSUE THREAD

**Issue by c0dingnoobi** [GrimAnticheat/RemoveHealthMetadata#1]
based on [wiki](https://wiki.vg/index.php?title=Entity_metadata&oldid=7415#Living_Entity_Base) it seems like 1.8 servers do have the health metadata as index `6` instead of `7` as defined in code.

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/RemoveHealthMetadata/commit/54a3e1f9b79ff5c47be4bdba3c1166f89c772e10
